/**
 * Fetch the tree-sitter query files referenced by parsers-config.ts and embed
 * them like the grammars.
 *
 * The runtime used to download each `.scm` on first use and cache it under the
 * OpenTUI data path — a network dependency for the first use of a language and
 * a cache that lived outside the worktree. The URLs stay the update source;
 * this script is the only place that reads them, at build time.
 *
 * Re-run with `--refresh` to pick up upstream changes:
 *   bun run script/fetch-queries.ts --refresh
 *
 * Outputs:
 *   assets/queries/<filetype>-<kind>-<n>.scm   (embedded assets, committed)
 *   src/util/wasm-embedded-queries.ts          (generated URL -> asset map)
 */
import fs from "node:fs/promises"
import path from "node:path"
import PARSER_CONFIG from "../parsers-config"

const ROOT = path.resolve(import.meta.dir, "..")
const ASSET_DIR = path.join(ROOT, "assets", "queries")
const GENERATED = path.join(ROOT, "src", "util", "wasm-embedded-queries.ts")
const refresh = process.argv.includes("--refresh")

type Kind = "highlights" | "injections"
interface QueryRef {
  filetype: string
  kind: Kind
  index: number
  url: string
}

function collect(): QueryRef[] {
  const refs: QueryRef[] = []
  for (const parser of PARSER_CONFIG.parsers) {
    const queries = parser.queries as { highlights?: string[]; injections?: string[] }
    for (const kind of ["highlights", "injections"] as const) {
      ;(queries[kind] ?? []).forEach((url, index) => refs.push({ filetype: parser.filetype, kind, index, url }))
    }
  }
  return refs
}

const fileName = (ref: QueryRef) => `${ref.filetype}-${ref.kind}-${ref.index}.scm`

async function download(ref: QueryRef, target: string): Promise<"cached" | "fetched"> {
  if (!refresh && (await fs.stat(target).catch(() => undefined))) return "cached"
  const response = await fetch(ref.url)
  if (!response.ok) throw new Error(`HTTP ${response.status} for ${ref.url}`)
  const text = await response.text()
  if (!text.trim()) throw new Error(`empty body for ${ref.url}`)
  await fs.writeFile(target, text)
  return "fetched"
}

const refs = collect()
await fs.mkdir(ASSET_DIR, { recursive: true })

const assets: Array<{ ref: QueryRef; file: string }> = []
const failures: string[] = []
for (const ref of refs) {
  const file = fileName(ref)
  try {
    const state = await download(ref, path.join(ASSET_DIR, file))
    console.log(`${state.padEnd(8)} ${file}`)
    assets.push({ ref, file })
  } catch (error) {
    failures.push(`${file} <- ${ref.url}: ${error instanceof Error ? error.message : String(error)}`)
    console.error(`FAILED   ${file} <- ${ref.url}`)
  }
}

const imports = assets
  .map((asset, i) => `import query${i} from "../../assets/queries/${asset.file}" with { type: "file" }`)
  .join("\n")
const entries = assets.map((asset, i) => `  [${JSON.stringify(asset.ref.url)}, query${i} as unknown as string],`).join("\n")

await fs.writeFile(
  GENERATED,
  `// Generated by script/fetch-queries.ts — do not edit by hand.
// Refresh: bun run script/fetch-queries.ts --refresh
${imports}

/** Query URL -> embedded asset path. Consumed by resolvedParsers in the TUI. */
export const embeddedQueryAssets = new Map<string, string>([
${entries}
])

export function embeddedQueryPath(url: string): string | undefined {
  return embeddedQueryAssets.get(url)
}

export const embeddedQueryPaths = [...embeddedQueryAssets.values()]
`,
)

console.log(`generated ${path.relative(ROOT, GENERATED)} with ${assets.length} queries`)
if (failures.length > 0) {
  console.error(`\n${failures.length} query URL(s) failed:`)
  for (const failure of failures) console.error(`- ${failure}`)
  process.exit(1)
}
