import path from "path"
import { fileURLToPath } from "url"

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)
const dir = path.resolve(__dirname, "..")

process.chdir(dir)

const modelsUrl = process.env.OPENCODE_MODELS_URL || "https://models.dev"
// Fetch and generate models.dev snapshot
const modelsData = process.env.MODELS_DEV_API_JSON
  ? await Bun.file(process.env.MODELS_DEV_API_JSON).text()
  : await fetch(`${modelsUrl}/api.json`).then((x) => x.text())

// Write per-provider JSON files
const data = JSON.parse(modelsData) as Record<string, unknown>
const modelsDir = path.join(dir, "src/provider/models")
await Bun.$`mkdir -p ${modelsDir}`.quiet()

for (const [providerID, providerData] of Object.entries(data)) {
  const filePath = path.join(modelsDir, `${providerID}.json`)
  await Bun.write(filePath, JSON.stringify(providerData))
}

// Keep original snapshot as fallback
await Bun.write(
  path.join(dir, "src/provider/models-snapshot.js"),
  `// @ts-nocheck\n// Auto-generated by build.ts - do not edit\nexport const snapshot = ${modelsData}\n`,
)
await Bun.write(
  path.join(dir, "src/provider/models-snapshot.d.ts"),
  `// Auto-generated by build.ts - do not edit\nexport declare const snapshot: Record<string, unknown>\n`,
)
console.log(`Generated models-snapshot.js + ${Object.keys(data).length} per-provider JSON files`)
