/**
 * Build-time entry for provider source sync — the runtime core lives in
 * src/provider/provider-sync.ts (types, converters, PROVIDER_SOURCES,
 * applyProviderOverrides, applyBundledOverrides). File writing stays
 * script-side so the runtime module carries no Bun-only IO.
 *
 * Running this file directly performs a targeted refresh: only the configured
 * providers are rewritten, based on the current models-snapshot.js — no full
 * models.dev fetch.
 */
import path from "path"
import { fileURLToPath } from "url"
import { applyProviderOverrides, PROVIDER_SOURCES } from "../src/provider/provider-sync"

export { applyProviderOverrides, PROVIDER_SOURCES }

/** Same outputs as generate.ts; onlyIds limits per-provider files to a subset. */
export async function writeRegistryOutputs(registry: Record<string, unknown>, dir: string, onlyIds?: string[]) {
  const modelsDir = path.join(dir, "src/provider/models")
  await Bun.$`mkdir -p ${modelsDir}`.quiet()

  let written = 0
  for (const [providerID, providerData] of Object.entries(registry)) {
    if (onlyIds && !onlyIds.includes(providerID)) continue
    await Bun.write(path.join(modelsDir, `${providerID}.json`), JSON.stringify(providerData))
    written++
  }
  await Bun.write(
    path.join(dir, "src/provider/models-snapshot.js"),
    `// @ts-nocheck\n// Auto-generated by build.ts - do not edit\nexport const snapshot = ${JSON.stringify(registry)}\n`,
  )
  await Bun.write(
    path.join(dir, "src/provider/models-snapshot.d.ts"),
    `// Auto-generated by build.ts - do not edit\nexport declare const snapshot: Record<string, unknown>\n`,
  )
  console.log(`Generated models-snapshot.js + ${written} per-provider JSON files (${onlyIds ? onlyIds.join(", ") : "full registry"})`)
}

// ---------- targeted standalone refresh ----------

if (import.meta.main) {
  const dir = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..")
  const { snapshot } = await import("../src/provider/models-snapshot.js")
  const registry = structuredClone(snapshot) as Record<string, unknown>
  await applyProviderOverrides(registry, { continueOnError: false })
  await writeRegistryOutputs(registry, dir, PROVIDER_SOURCES.map((s) => s.id))
}
