import fs from "fs/promises"
import path from "path"
import { parse as parseJsonc } from "jsonc-parser"
import { Global } from "@opencode-ai/core/global"
import * as Log from "@opencode-ai/core/util/log"
import { Filesystem } from "@/util/filesystem"
import { ModelsDev } from "../models"
import type { ProviderID } from "../schema"

const log = Log.create({ service: "gateway.config-manager" })

const GLOBAL_GATEWAY_FILE = path.join(Global.Path.config, "gateway.jsonc")
const AUTO_GENERATED_MARKER = "// AUTO-GENERATED by opencode - user edits below this line will be preserved"

function getLocalGatewayFile(): string {
  return path.join(process.cwd(), ".opencode", "gateway.jsonc")
}

const DEFAULT_TIMEOUT = 1800000
const DEFAULT_CHUNK_TIMEOUT = 600000
let cachedConfig: GatewayConfig | null = null
const ensuredModels = new Set<string>()
let configTimestamp = 0

export interface GatewayProviderConfig {
  name?: string
  env?: readonly string[]
  api?: string
  npm?: string
  models: Record<string, GatewayModelConfig>
  options?: Record<string, unknown>
}

export interface GatewayModelConfig {
  id?: string
  name?: string
  baseURL?: string
  limit?: {
    context?: number
    output?: number
    input?: number
  }
  gateway?: {
    enabled?: boolean
    debug?: boolean
    logging?: {
      enabled?: boolean
      format?: "json" | "text"
      logBodies?: boolean
      maxBodySize?: number
    }
  }
  provider?: {
    npm?: string
    api?: string
  }
  options?: Record<string, unknown>
  metadata?: {
    context_window?: number
    max_output?: number
    supports_reasoning?: boolean
    supports_attachments?: boolean
    cost_per_million?: {
      input?: number
      output?: number
      cache_read?: number
      cache_write?: number
    }
  }
}

export interface GatewayConfig {
  $schema?: string
  providers: Record<string, GatewayProviderConfig>
  gateway?: {
    enabled?: boolean
    debug?: boolean
    logging?: {
      enabled?: boolean
      format?: "json" | "text"
      logBodies?: boolean
      maxBodySize?: number
    }
  }
}

function defaultModelConfig(provider: ModelsDev.Provider, model: ModelsDev.Model): GatewayModelConfig {
  return {
    id: model.id,
    name: model.name,
    baseURL: model.provider?.api ?? provider.api,
    gateway: {
      logging: {
        enabled: false,
        format: "json",
      },
    },
    provider: {
      npm: model.provider?.npm ?? provider.npm ?? "@ai-sdk/openai-compatible",
      api: model.provider?.api ?? provider.api,
    },
    limit: {
      context: model.limit?.context,
      output: model.limit?.output,
    },
    metadata: {
      context_window: model.limit?.context,
      max_output: model.limit?.output,
      supports_reasoning: model.reasoning ?? false,
      supports_attachments: model.attachment ?? false,
      cost_per_million: model.cost
        ? {
            input: model.cost.input,
            output: model.cost.output,
            cache_read: model.cost.cache_read,
            cache_write: model.cost.cache_write,
          }
        : undefined,
    },
  }
}

function defaultProviderConfig(
  provider: ModelsDev.Provider,
  modelId: string,
  model: ModelsDev.Model,
): GatewayProviderConfig {
  return {
    name: provider.name,
    env: provider.env ?? [],
    api: provider.api,
    npm: provider.npm,
    models: {
      [modelId]: defaultModelConfig(provider, model),
    },
    options: {
      timeout: 1800000,
      chunkTimeout: 600000,
    },
  }
}

async function readConfigFile(filePath: string): Promise<GatewayConfig | null> {
  try {
    const text = await Filesystem.readText(filePath)
    // Strip auto-generated marker and everything before it for manual edits
    const cleaned = text.includes(AUTO_GENERATED_MARKER) ? (text.split(AUTO_GENERATED_MARKER)[1] ?? text) : text
    const parsed = parseJsonc(cleaned) as GatewayConfig
    return parsed
  } catch {
    return null
  }
}

export async function writeConfigFile(filePath: string, config: GatewayConfig): Promise<void> {
  await fs.mkdir(path.dirname(filePath), { recursive: true })

  const content = `${AUTO_GENERATED_MARKER}
//
// Gateway Configuration (JSONC - comments are supported)
// This file controls the opencode gateway (HTTP proxy for LLM requests).
//
// API keys and OAuth tokens are NOT stored here. They are managed via
// opencode's auth system (~/.local/share/opencode/auth.json).
//
// GLOBAL GATEWAY SETTINGS
// -----------------------
// gateway.enabled: Enable or disable the gateway. Default: true.
// gateway.debug: Enable debug mode for gateway internals. Default: false.
// gateway.logging.enabled: Enable gateway request logging. Default: false.
// gateway.logging.format: Log format - "json" or "text". Default: "json".
// gateway.logging.logBodies: Include request/response bodies in logs. Default: false.
// gateway.logging.maxBodySize: Max body size in bytes to include in logs. Default: 10000.
//
// PROVIDER SETTINGS
// -----------------
// Each provider in "providers" has these settings:
// providers.<name>.name: Human-readable provider name.
// providers.<name>.env: Environment variable names required for this provider
//   (e.g. ["OPENAI_API_KEY"]). Values are read from auth system, not this file.
// providers.<name>.api: API base URL for the provider.
// providers.<name>.npm: NPM package for the provider SDK
//   (e.g. "@ai-sdk/openai-compatible", "@ai-sdk/anthropic").
// providers.<name>.options.timeout: Total request timeout in milliseconds.
//   Default: 1800000 (30 minutes).
// providers.<name>.options.chunkTimeout: Idle timeout between streaming chunks
//   in milliseconds. Default: 600000 (10 minutes).
//
// MODEL SETTINGS
// --------------
// Each model under a provider can override settings:
// providers.<name>.models.<model>.gateway.enabled: Override gateway enabled for this model.
// providers.<name>.models.<model>.gateway.debug: Enable debug mode for this model.
// providers.<name>.models.<model>.gateway.logging.*: Override logging settings for this model.
// providers.<name>.models.<model>.provider.api: Override API URL for this model.
// providers.<name>.models.<model>.provider.npm: Override NPM package for this model.
// providers.<name>.models.<model>.limit.context: Context window size in tokens.
// providers.<name>.models.<model>.limit.output: Maximum output tokens.
// providers.<name>.models.<model>.metadata.*: Model metadata (cost, capabilities, etc.).
//

${JSON.stringify(config, null, 2)}
`
  const tempPath = filePath + ".tmp"

  await fs.writeFile(tempPath, content)
  await fs.rename(tempPath, filePath)

  log.debug("wrote gateway config", { path: filePath })
}

async function mergeConfigs(
  globalConfig: GatewayConfig | null,
  localConfig: GatewayConfig | null,
): Promise<GatewayConfig> {
  const result: GatewayConfig = {
    $schema: "https://opencode.ai/config.json",
    providers: {},
    gateway: {
      enabled: true,
      logging: {
        enabled: false,
        format: "json",
      },
    },
  }

  // Start with global config as base
  if (globalConfig) {
    result.gateway = { ...result.gateway, ...globalConfig.gateway }
    result.providers = { ...globalConfig.providers }
  }

  // Merge local config (local overrides global)
  if (localConfig) {
    result.gateway = { ...result.gateway, ...localConfig.gateway }
    for (const [providerId, provider] of Object.entries(localConfig.providers)) {
      const existing = result.providers[providerId]
      if (existing) {
        // Deep merge provider - preserve global settings not explicitly overridden locally
        result.providers[providerId] = {
          ...existing,
          ...provider,
          api: provider.api ?? existing.api,
          npm: provider.npm ?? existing.npm,
          name: provider.name ?? existing.name,
          env: provider.env ?? existing.env,
          models: {
            ...existing.models,
            ...provider.models,
          },
        }
      } else {
        result.providers[providerId] = provider
      }
    }
  }

  for (const provider of Object.values(result.providers)) {
    if (!provider.options) provider.options = {}
    provider.options.timeout = DEFAULT_TIMEOUT
    provider.options.chunkTimeout = DEFAULT_CHUNK_TIMEOUT
  }

  return result
}

export async function ensureGatewayConfig(): Promise<void> {
  const globalConfig = await readConfigFile(GLOBAL_GATEWAY_FILE)
  const localConfigPath = getLocalGatewayFile()
  const localConfig = await readConfigFile(localConfigPath)

  if (!globalConfig && !localConfig) {
    const defaultConfig = await buildDefaultConfig()
    await writeConfigFile(GLOBAL_GATEWAY_FILE, defaultConfig)
    log.info("created default global gateway config", {
      path: GLOBAL_GATEWAY_FILE,
      providerCount: Object.keys(defaultConfig.providers).length,
    })
  } else if (!globalConfig && localConfig) {
    const defaultConfig = await buildDefaultConfig()
    await writeConfigFile(GLOBAL_GATEWAY_FILE, defaultConfig)
    log.info("created missing global gateway config", { path: GLOBAL_GATEWAY_FILE })
  } else if (globalConfig && !localConfig) {
    await writeConfigFile(localConfigPath, globalConfig)
    log.info("created local gateway config from global", { path: localConfigPath })
  } else if (globalConfig && Object.keys(globalConfig.providers).length === 0) {
    const defaultConfig = await buildDefaultConfig()
    await writeConfigFile(GLOBAL_GATEWAY_FILE, defaultConfig)
    log.info("populated empty gateway config with recent models", {
      path: GLOBAL_GATEWAY_FILE,
      providerCount: Object.keys(defaultConfig.providers).length,
    })
  }
}

async function buildDefaultConfig(): Promise<GatewayConfig> {
  let recentModels: Array<{ providerID: string; modelID: string }> = []
  try {
    const statePath = path.join(Global.Path.state, "model.json")
    const stateText = await Filesystem.readText(statePath)
    const state = JSON.parse(stateText)
    if (Array.isArray(state.recent)) recentModels = state.recent
  } catch {
    // No state file or parse error — proceed with empty recent
  }

  const models = await ModelsDev.get()
  const providers: Record<string, GatewayProviderConfig> = {}

  for (const { providerID, modelID } of recentModels) {
    const devProvider = models[providerID]
    if (!devProvider) continue
    const devModel = devProvider.models[modelID]
    if (!devModel) continue

    if (!providers[providerID]) {
      providers[providerID] = {
        name: devProvider.name,
        env: devProvider.env ?? [],
        api: devProvider.api,
        npm: devProvider.npm,
        models: {},
        options: {
          timeout: DEFAULT_TIMEOUT,
          chunkTimeout: DEFAULT_CHUNK_TIMEOUT,
        },
      }
    }
    providers[providerID].models[modelID] = defaultModelConfig(devProvider, devModel)
  }

  return {
    $schema: "https://opencode.ai/config.json",
    providers,
    gateway: {
      enabled: true,
      logging: {
        enabled: false,
        format: "json",
      },
    },
  }
}

export async function ensureModelConfig(providerID: ProviderID, modelID: string): Promise<void> {
  const key = `${providerID}/${modelID}`
  if (ensuredModels.has(key)) {
    return
  }
  ensuredModels.add(key)

  log.debug("ensuring model config", { providerID, modelID })

  const globalConfig = await readConfigFile(GLOBAL_GATEWAY_FILE)
  const localConfigPath = getLocalGatewayFile()
  const localConfig = await readConfigFile(localConfigPath)

  // Check if model is already configured in either global or local
  const merged = await mergeConfigs(globalConfig, localConfig)
  const provider = merged.providers[providerID]
  if (provider?.models?.[modelID]) {
    log.debug("model already configured, skipping", { providerID, modelID })
    return
  }

  // Fetch model info from ModelsDev
  const models = await ModelsDev.get()
  const devProvider = models[providerID]
  if (!devProvider) {
    log.debug("provider not found in models.dev, skipping auto-config", { providerID })
    return
  }

  const devModel = devProvider.models[modelID]
  if (!devModel) {
    log.debug("model not found in models.dev, skipping auto-config", { providerID, modelID })
    return
  }

  // Generate config for this model
  const modelConfig = defaultModelConfig(devProvider, devModel)

  // Update global config first (as the canonical source)
  const existingProvider = globalConfig?.providers?.[providerID]
  const updatedGlobal: GatewayConfig = {
    ...(globalConfig || {
      $schema: "https://opencode.ai/config.json",
      providers: {},
      gateway: {
        enabled: true,
        logging: { enabled: false, format: "json" },
      },
    }),
    providers: {
      ...(globalConfig?.providers || {}),
      [providerID]: {
        name: devProvider.name,
        env: devProvider.env ?? [],
        api: devProvider.api,
        npm: devProvider.npm,
        models: {
          ...(existingProvider?.models || {}),
          [modelID]: modelConfig,
        },
        options: existingProvider?.options || {
          timeout: DEFAULT_TIMEOUT,
          chunkTimeout: DEFAULT_CHUNK_TIMEOUT,
        },
      },
    },
  }

  await writeConfigFile(GLOBAL_GATEWAY_FILE, updatedGlobal)
  log.info("auto-generated model config in global gateway.jsonc", {
    providerID,
    modelID,
    path: GLOBAL_GATEWAY_FILE,
  })

  // If local config exists but doesn't have this model, sync from global
  if (localConfig && !localConfig.providers?.[providerID]?.models?.[modelID]) {
    const existingLocalProvider = localConfig.providers?.[providerID]
    const updatedProvider = {
      name: devProvider.name,
      env: devProvider.env ?? [],
      api: devProvider.api,
      npm: devProvider.npm,
      models: {
        ...(existingLocalProvider?.models || {}),
        [modelID]: modelConfig,
      },
      options: existingLocalProvider?.options || {
        timeout: DEFAULT_TIMEOUT,
        chunkTimeout: DEFAULT_CHUNK_TIMEOUT,
      },
    }

    const updatedLocal: GatewayConfig = {
      ...localConfig,
      providers: {
        ...localConfig.providers,
        [providerID]: updatedProvider,
      },
    }

    await writeConfigFile(localConfigPath, updatedLocal)
    log.info("synced model config from global to local", {
      providerID,
      modelID,
      path: localConfigPath,
    })
  }
}

export async function loadGatewayConfig(): Promise<GatewayConfig> {
  await ensureGatewayConfig()

  const globalConfig = await readConfigFile(GLOBAL_GATEWAY_FILE)
  const localConfigPath = getLocalGatewayFile()
  const localConfig = await readConfigFile(localConfigPath)

  return mergeConfigs(globalConfig, localConfig)
}

export async function getProviderConfig(providerID: string): Promise<GatewayProviderConfig | null> {
  const config = await loadGatewayConfig()
  return config.providers[providerID] || null
}

export async function getModelConfig(providerID: string, modelID: string): Promise<GatewayModelConfig | null> {
  const config = await loadGatewayConfig()
  return config.providers[providerID]?.models?.[modelID] || null
}

export async function isGloballyEnabled(): Promise<boolean> {
  const config = await loadGatewayConfig()
  return config.gateway?.enabled !== false
}

export async function isModelEnabled(providerID: string, modelID: string): Promise<boolean> {
  const config = await loadGatewayConfig()
  const model = config.providers[providerID]?.models?.[modelID]
  if (model?.gateway?.enabled !== undefined) {
    return model.gateway.enabled
  }
  return config.gateway?.enabled !== false
}


