"""Semantic Map — cosine similarity matrix + top-3 neighbors + flow ordering.

The main entry point for kernel dictionary semantic analysis.
Combines dictionary extraction, DeepResolution, embedding, similarity,
and Maximum Adjacency Similarity flow sorting.

Usage:
  python -m prompts_kernel.tools.semantic_map                  # full pipeline
  python -m prompts_kernel.tools.semantic_map --top 5          # top-5 neighbors
  python -m prompts_kernel.tools.semantic_map --dictionary-only # rules+terms only
  python -m prompts_kernel.tools.semantic_map --types rule,term # specific types
  python -m prompts_kernel.tools.semantic_map --gated G1,G2,G3,G4,G5,G6,G7,G8,G9  # gated chain
  python -m prompts_kernel.tools.semantic_map --gated G1,G2,G3 --candidates 5     # top-5 chains
  python -m prompts_kernel.tools.semantic_map --flow           # flow order only
  python -m prompts_kernel.tools.semantic_map --json           # JSON output
"""

from __future__ import annotations

import json
import sys
import time
from dataclasses import dataclass, field

import numpy as np


@dataclass
class Neighbor:
    id: str
    similarity: float
    entry_type: str = ""


@dataclass
class SemanticReport:
    entry_id: str
    entry_type: str
    category: str
    top_neighbors: list[Neighbor] = field(default_factory=list)
    body_size_raw: int = 0
    body_size_resolved: int = 0


def cosine_similarity_matrix(vectors: dict[str, np.ndarray]) -> tuple[list[str], np.ndarray]:
    """Compute N×N cosine similarity matrix from L2-normalized vectors.

    Since vectors are already normalized, dot product = cosine similarity.
    Returns (ids_ordered, matrix) where matrix[i][j] = cos(id_i, id_j).
    """
    ids = sorted(vectors.keys())
    n = len(ids)
    # Stack into (N, D) array
    V = np.stack([vectors[eid] for eid in ids])  # (N, D)
    # Cosine = dot product (vectors are already normalized)
    matrix = V @ V.T  # (N, N)
    return ids, matrix


def top_k_neighbors(
    ids: list[str],
    matrix: np.ndarray,
    k: int = 3,
) -> dict[str, list[Neighbor]]:
    """For each entry, find its top-k nearest neighbors (excluding self)."""
    result: dict[str, list[Neighbor]] = {}
    n = len(ids)

    for i, eid in enumerate(ids):
        # Get row i, exclude self (diagonal = 1.0)
        row = matrix[i].copy()
        row[i] = -1.0  # exclude self
        # Top-k indices
        top_indices = np.argsort(row)[-k:][::-1]
        neighbors = [
            Neighbor(
                id=ids[j],
                similarity=float(row[j]),
            )
            for j in top_indices
        ]
        result[eid] = neighbors

    return result


def flow_order_greedy(
    ids: list[str],
    matrix: np.ndarray,
    seed: str | None = None,
) -> list[str]:
    """Greedy Maximum Adjacency Similarity (MAS) flow ordering.

    Starting from a seed entry, repeatedly add the highest-similarity
    unvisited neighbor. This produces a Hamiltonian path that approximates
    the optimal MAS ordering (NP-hard TSP reduction).

    If no seed is provided, start from the entry with highest average
    similarity (most central).
    """
    n = len(ids)
    if n <= 1:
        return list(ids)

    # Choose seed: highest average similarity
    if seed is None:
        avg_sims = matrix.mean(axis=1)
        seed_idx = int(np.argmax(avg_sims))
    else:
        try:
            seed_idx = ids.index(seed)
        except ValueError:
            seed_idx = 0

    visited = {seed_idx}
    order = [ids[seed_idx]]
    current = seed_idx

    while len(visited) < n:
        # Find highest-similarity unvisited neighbor
        best_idx = -1
        best_sim = -2.0
        for j in range(n):
            if j not in visited and matrix[current][j] > best_sim:
                best_sim = matrix[current][j]
                best_idx = j

        if best_idx < 0:
            # Disconnected graph — pick any unvisited
            for j in range(n):
                if j not in visited:
                    best_idx = j
                    break

        if best_idx >= 0:
            visited.add(best_idx)
            order.append(ids[best_idx])
            current = best_idx
        else:
            break

    return order


def gated_chain_candidates(
    ids: list[str],
    matrix: np.ndarray,
    gated: list[str],
    num_candidates: int = 3,
) -> list[list[str]]:
    """Generate candidate chains with fixed gated entries + optimal free placement.

    Gated entries form a fixed backbone (e.g., G1→G2→...→G9). Free entries
    are inserted into the gaps between gated entries to minimize total chain
    delta (sum of 1-cosine between adjacent entries).

    Multiple candidates are generated by varying insertion heuristics:
    - Candidate 1: greedy — each free entry goes to its single best gap
    - Candidate 2: balanced — distribute free entries evenly across gaps
    - Candidate 3+: shuffled insertion order to explore local optima

    Returns list of candidate chains (each a full ordering of all ids).
    """
    id_to_idx = {eid: i for i, eid in enumerate(ids)}
    n = len(ids)

    # Validate gated entries exist in ids
    gated_present = [g for g in gated if g in id_to_idx]
    if len(gated_present) < 2:
        # Fallback: return ungated flow order
        return [flow_order_greedy(ids, matrix)]

    gated_indices = [id_to_idx[g] for g in gated_present]
    free_indices = [i for i in range(n) if i not in set(gated_indices)]

    def chain_delta(chain_indices: list[int]) -> float:
        """Total delta (1-cosine) along a chain. Lower = better."""
        d = 0.0
        for a, b in zip(chain_indices[:-1], chain_indices[1:]):
            d += 1.0 - matrix[a][b]
        return d

    def similarity(a: int, b: int) -> float:
        return float(matrix[a][b])

    # ── Gap structure ──
    # Gaps between consecutive gated entries: gap[i] is between gated[i] and gated[i+1]
    num_gaps = len(gated_indices) - 1
    gap_free: list[list[int]] = [[] for _ in range(num_gaps)]
    # Also gaps before first gated and after last gated
    gap_pre: list[int] = []
    gap_post: list[int] = []

    candidates: list[list[str]] = []

    # ── Candidate 1: Greedy best-fit per free entry ──
    for fi in free_indices:
        best_gap = -1
        best_score = -2.0
        # Check each internal gap
        for g in range(num_gaps):
            left = gated_indices[g]
            right = gated_indices[g + 1]
            # Score: how well fi fits between left and right
            score = similarity(left, fi) + similarity(fi, right) - similarity(left, right)
            if score > best_score:
                best_score = score
                best_gap = g
        # Check pre-gap (before first gated)
        score_pre = similarity(fi, gated_indices[0])
        if score_pre > best_score:
            best_score = score_pre
            best_gap = -1  # pre
        # Check post-gap (after last gated)
        score_post = similarity(gated_indices[-1], fi)
        if score_post > best_score:
            best_score = score_post
            best_gap = num_gaps  # post

        if best_gap == -1:
            gap_pre.append(fi)
        elif best_gap == num_gaps:
            gap_post.append(fi)
        else:
            gap_free[best_gap].append(fi)

    # Within each gap, sort by similarity to surrounding gated entries
    def sort_by_fit(free_list: list[int], left_idx: int | None, right_idx: int | None):
        if left_idx is not None and right_idx is not None:
            free_list.sort(key=lambda fi: -(similarity(left_idx, fi) + similarity(fi, right_idx)))
        elif left_idx is not None:
            free_list.sort(key=lambda fi: -similarity(left_idx, fi))
        elif right_idx is not None:
            free_list.sort(key=lambda fi: -similarity(fi, right_idx))

    sort_by_fit(gap_pre, None, gated_indices[0])
    for g in range(num_gaps):
        sort_by_fit(gap_free[g], gated_indices[g], gated_indices[g + 1])
    sort_by_fit(gap_post, gated_indices[-1], None)

    # Build chain
    chain1: list[int] = list(gap_pre)
    for g in range(num_gaps):
        chain1.append(gated_indices[g])
        chain1.extend(gap_free[g])
    chain1.append(gated_indices[-1])
    chain1.extend(gap_post)

    candidates.append([ids[i] for i in chain1])

    # ── Candidate 2: Balanced distribution ──
    # Distribute free entries evenly: sort all free by avg similarity to all gated,
    # then round-robin assign to gaps
    free_sorted = sorted(free_indices, key=lambda fi: -sum(similarity(fi, gi) for gi in gated_indices))
    gap_free2: list[list[int]] = [[] for _ in range(num_gaps + 2)]  # pre, internal..., post
    for k, fi in enumerate(free_sorted):
        gap_idx = k % (num_gaps + 2)
        gap_free2[gap_idx].append(fi)

    for g in range(len(gap_free2)):
        left = gated_indices[g - 1] if 0 < g <= num_gaps else (None if g == 0 else gated_indices[-1])
        right = gated_indices[g] if g < num_gaps else (gated_indices[-1] if g == num_gaps else None)
        # left=None,right=first for gap 0; left=last,right=None for last gap
        if g == 0:
            sort_by_fit(gap_free2[g], None, gated_indices[0])
        elif g <= num_gaps:
            sort_by_fit(gap_free2[g], gated_indices[g - 1], gated_indices[g])
        else:
            sort_by_fit(gap_free2[g], gated_indices[-1], None)

    chain2: list[int] = list(gap_free2[0])
    for g in range(num_gaps):
        chain2.append(gated_indices[g])
        chain2.extend(gap_free2[g + 1])
    chain2.append(gated_indices[-1])
    chain2.extend(gap_free2[-1])

    candidates.append([ids[i] for i in chain2])

    # ── Candidate 3+: Shuffled insertion order ──
    import random
    rng = random.Random(42)  # deterministic seed
    for cand_idx in range(num_candidates - 2):
        shuffled_free = list(free_indices)
        rng.shuffle(shuffled_free)

        gap_free3: list[list[int]] = [[] for _ in range(num_gaps)]
        gap_pre3: list[int] = []
        gap_post3: list[int] = []

        for fi in shuffled_free:
            best_gap = -1
            best_score = -2.0
            for g in range(num_gaps):
                left = gated_indices[g]
                right = gated_indices[g + 1]
                score = similarity(left, fi) + similarity(fi, right)
                if score > best_score:
                    best_score = score
                    best_gap = g
            score_pre = similarity(fi, gated_indices[0])
            if score_pre > best_score:
                best_score = score_pre
                best_gap = -1
            score_post = similarity(gated_indices[-1], fi)
            if score_post > best_score:
                best_score = score_post
                best_gap = num_gaps

            if best_gap == -1:
                gap_pre3.append(fi)
            elif best_gap == num_gaps:
                gap_post3.append(fi)
            else:
                gap_free3[best_gap].append(fi)

        sort_by_fit(gap_pre3, None, gated_indices[0])
        for g in range(num_gaps):
            sort_by_fit(gap_free3[g], gated_indices[g], gated_indices[g + 1])
        sort_by_fit(gap_post3, gated_indices[-1], None)

        chain3: list[int] = list(gap_pre3)
        for g in range(num_gaps):
            chain3.append(gated_indices[g])
            chain3.extend(gap_free3[g])
        chain3.append(gated_indices[-1])
        chain3.extend(gap_post3)

        cand_chain = [ids[i] for i in chain3]
        if cand_chain not in candidates:
            candidates.append(cand_chain)

    return candidates[:num_candidates]


def _chain_delta(chain: list[str], ids: list[str], matrix: np.ndarray) -> float:
    """Compute total delta (1-cosine) for a chain of entry IDs."""
    d = 0.0
    id_to_idx = {eid: i for i, eid in enumerate(ids)}
    for a, b in zip(chain[:-1], chain[1:]):
        if a in id_to_idx and b in id_to_idx:
            d += 1.0 - float(matrix[id_to_idx[a]][id_to_idx[b]])
    return d


def build_report(
    entries: dict,
    vectors: dict[str, np.ndarray],
    neighbors: dict[str, list[Neighbor]],
    bodies: dict[str, str],
    bodies_raw: dict[str, str],
) -> list[SemanticReport]:
    """Build semantic reports with metadata."""
    reports = []
    for eid in sorted(neighbors.keys()):
        e = entries.get(eid)
        reports.append(SemanticReport(
            entry_id=eid,
            entry_type=e.type if e else "?",
            category=e.category if e else "",
            top_neighbors=neighbors[eid],
            body_size_raw=len(bodies_raw.get(eid, "")),
            body_size_resolved=len(bodies.get(eid, "")),
        ))
    return reports


def main() -> int:
    from prompts_kernel.tools.dictionary import parse_dictionary, resolve_all, Entry
    from prompts_kernel.tools.embed import compute_embeddings

    k = 3
    json_mode = "--json" in sys.argv
    log = sys.stderr if json_mode else sys.stdout

    # ── Type filter ──
    if "--dictionary-only" in sys.argv:
        type_filter = {"rule", "term", "schema", "diagram", "algorithm", "epistemic"}
    elif "--types" in sys.argv:
        idx = sys.argv.index("--types")
        type_filter = set(sys.argv[idx + 1].split(",")) if idx + 1 < len(sys.argv) else None
    else:
        type_filter = None

    # ── Gated chain ──
    gated: list[str] = []
    num_candidates = 3
    if "--gated" in sys.argv:
        idx = sys.argv.index("--gated")
        if idx + 1 < len(sys.argv):
            gated = [g.strip() for g in sys.argv[idx + 1].split(",")]
    if "--candidates" in sys.argv:
        idx = sys.argv.index("--candidates")
        if idx + 1 < len(sys.argv):
            num_candidates = int(sys.argv[idx + 1])

    if "--top" in sys.argv:
        idx = sys.argv.index("--top")
        if idx + 1 < len(sys.argv):
            k = int(sys.argv[idx + 1])

    print("─" * 60, file=log)
    print("Step 1/5: Parse dictionary...", file=log)
    t0 = time.time()
    entries = parse_dictionary()
    print(f"  {len(entries)} entries ({time.time() - t0:.1f}s)", file=log)

    print("Step 2/5: Raw bodies (no DeepResolution)...", file=log)
    t0 = time.time()
    bodies_raw = {eid: e.body for eid, e in entries.items()}
    print(f"  {len(bodies_raw)} raw bodies ({time.time() - t0:.1f}s)", file=log)
    sizes = [len(v) for v in bodies_raw.values()]
    print(f"  Size: min={min(sizes)}, max={max(sizes)}, avg={sum(sizes)//len(sizes)}", file=log)

    print("Step 3/5: Embedding (BGE-base-en-v1.5) on raw bodies...", file=log)
    t0 = time.time()
    vectors = compute_embeddings(bodies_raw)
    print(f"  {len(vectors)} vectors ({time.time() - t0:.1f}s)", file=log)

    # ── Filter to selected types ──
    if type_filter:
        # Always include gated entries even if they don't match the type filter
        keep_ids = set()
        for eid, vec in vectors.items():
            if eid in entries and entries[eid].type in type_filter:
                keep_ids.add(eid)
        if gated:
            keep_ids.update(gated)
        vectors = {eid: vec for eid, vec in vectors.items() if eid in keep_ids}
        print(f"  Filtered to {len(vectors)} entries (types: {type_filter}, +gated)", file=log)

    print("Step 4/5: Cosine similarity matrix + top-k...", file=log)
    t0 = time.time()
    ids, matrix = cosine_similarity_matrix(vectors)
    neighbors = top_k_neighbors(ids, matrix, k=k)
    print(f"  {len(ids)}×{len(ids)} matrix, top-{k} neighbors ({time.time() - t0:.1f}s)", file=log)

    # Gather raw bodies for size comparison
    bodies_raw = {eid: e.body for eid, e in entries.items()}

    print("Step 5/5: Flow ordering...", file=log)
    t0 = time.time()
    if gated:
        chains = gated_chain_candidates(ids, matrix, gated, num_candidates)
        order = chains[0]  # primary chain = best candidate
        print(f"  {len(chains)} gated chains, {len(order)} entries each ({time.time() - t0:.1f}s)", file=log)
    else:
        order = flow_order_greedy(ids, matrix)
        chains = None
        print(f"  {len(order)} entries ordered ({time.time() - t0:.1f}s)", file=log)

    # ── Output ──
    reports = build_report(entries, vectors, neighbors, bodies_raw, bodies_raw)

    if "--json" in sys.argv:
        out: dict = {
            "pipeline": {
                "entries": len(vectors),
                "total_parsed": len(entries),
                "vectors_dim": 768,
                "model": "BAAI/bge-base-en-v1.5",
                "resolution": "raw",
                "type_filter": list(type_filter) if type_filter else None,
                "gated": gated if gated else None,
            },
            "flow_order": order,
            "entries": {},
        }
        if chains and len(chains) > 1:
            out["candidate_chains"] = [
                {"rank": i + 1, "chain": c, "delta": round(_chain_delta(c, ids, matrix), 4)}
                for i, c in enumerate(chains)
            ]
        # Build entries dict in flow order (preserved in Python 3.7+)
        for eid in order:
            e = entries.get(eid)
            if eid not in neighbors:
                continue
            out["entries"][eid] = {
                "type": e.type if e else "?",
                "category": e.category if e else "",
                "body_raw": e.body if e else "",
                "body_size": len(e.body) if e else 0,
                "top_neighbors": [
                    {
                        "id": n.id,
                        "similarity": round(n.similarity, 4),
                        "type": entries[n.id].type if n.id in entries else "?",
                        "body_raw": entries[n.id].body if n.id in entries else "",
                    }
                    for n in neighbors[eid]
                ],
            }
        print(json.dumps(out, indent=2, ensure_ascii=False))
        return 0

    if "--flow" in sys.argv:
        if chains and len(chains) > 1:
            print(f"\n=== Gated Chain Candidates ({len(chains)} chains, gated: {gated}) ===")
            for ci, chain in enumerate(chains):
                delta = _chain_delta(chain, ids, matrix)
                gated_positions = [i for i, eid in enumerate(chain) if eid in gated]
                print(f"\n  Candidate {ci+1} — delta={delta:.4f}, gated at: {gated_positions}")
                for i, eid in enumerate(chain):
                    e = entries.get(eid)
                    etype = e.type if e else "?"
                    marker = " ◀◀ GATED" if eid in gated else ""
                    print(f"    {i+1:3d}. {eid:<35} [{etype}]{marker}")
        else:
            print("\n=== Flow Order (MAS Greedy) ===")
            for i, eid in enumerate(order):
                e = entries.get(eid)
                etype = e.type if e else "?"
                print(f"  {i+1:3d}. {eid:<35} [{etype}]")
        return 0

    # Default: formatted table
    print(f"\n{'='*80}")
    print(f"Kernel Dictionary Semantic Map — Top-{k} Neighbors")
    print(f"{'='*80}")
    print(f"{'Entry':<30} {'Type':<12} {'Top Neighbors (similarity)'}")
    print(f"{'-'*30} {'-'*12} {'-'*40}")

    for r in reports:
        nb_str = "  ".join(
            f"{n.id}({n.similarity:.3f})" for n in r.top_neighbors
        )
        print(f"{r.entry_id:<30} {r.entry_type:<12} {nb_str}")

    # Flow order summary
    print(f"\n{'='*80}")
    print(f"Flow Order (MAS Greedy) — {len(order)} entries")
    print(f"{'='*80}")
    # Show first 20 and last 10
    for i, eid in enumerate(order[:20]):
        e = entries.get(eid)
        etype = e.type if e else "?"
        cat = f"[{e.category}]" if e and e.category else ""
        print(f"  {i+1:3d}. {eid:<35} {etype:<12} {cat}")
    if len(order) > 30:
        print(f"  ... ({len(order) - 30} entries omitted) ...")
    for i, eid in enumerate(order[-10:]):
        idx = len(order) - 10 + i + 1
        e = entries.get(eid)
        etype = e.type if e else "?"
        cat = f"[{e.category}]" if e and e.category else ""
        print(f"  {idx:3d}. {eid:<35} {etype:<12} {cat}")

    # Similarity stats
    all_sims = [n.similarity for r in reports for n in r.top_neighbors]
    print(f"\nSimilarity stats (top-{k}):")
    print(f"  Min: {min(all_sims):.4f}  Max: {max(all_sims):.4f}  Mean: {sum(all_sims)/len(all_sims):.4f}")

    return 0


if __name__ == "__main__":
    sys.exit(main())
