"""Kernel fragment: 29_reasoning_render — assemble reasoning.txt from fragments.

Source fragments live in:
  packages/opencode/src/session/prompt/reasoning/*.txt

Fragments are concatenated in sorted filename order (00_, 01_, …).
Single blank line between fragment bodies; final newline.
"""
from __future__ import annotations

from pathlib import Path


def _default_fragment_dir() -> Path:
    """Resolve the fragment directory — co-located in kernel package."""
    return Path(__file__).resolve().parent / "reasoning"


def _default_output() -> Path:
    """Default output path for reasoning.txt (packages/opencode/src/session/prompt/)."""
    kernel_dir = Path(__file__).resolve().parent  # opencode_prompts_kernel/
    repo_root = kernel_dir.parent
    return repo_root / "packages" / "opencode" / "src" / "session" / "prompt" / "reasoning.txt"


def assemble_reasoning(fragment_dir: Path | None = None) -> str:
    """Assemble reasoning.txt from topic fragments.

    Fragments are sorted by filename and joined with double-newline separators.
    Returns the assembled text (UTF-8, LF endings).
    """
    if fragment_dir is None:
        fragment_dir = _default_fragment_dir()

    files = sorted(fragment_dir.glob("*.txt"))
    if not files:
        raise FileNotFoundError(f"no fragments in {fragment_dir}")

    parts: list[str] = []
    for path in files:
        text = path.read_text(encoding="utf-8")
        if not text.endswith("\n"):
            text += "\n"
        parts.append(text.rstrip("\n"))

    return "\n\n".join(parts) + "\n"


def write_reasoning(output: Path | None = None, fragment_dir: Path | None = None) -> int:
    """Write reasoning.txt from fragments. Returns byte count written."""
    body = assemble_reasoning(fragment_dir)
    if output is None:
        output = _default_output()
    output.write_text(body, encoding="utf-8", newline="\n")
    return len(body)


# =========================================================================
# Precompiled kernel module — 10× import speedup
# =========================================================================

# Mirrors __init__._FRAGMENTS and __init__._COMMON_IMPORTS.
# Duplicated intentionally: _assemble_prompts_kernel is loaded BEFORE
# __init__ finishes bootstrapping, so we can't import from __init__.
_PRECOMPILE_FRAGMENTS: list[str] = [
    "01_enums",
    "02_info_mark",
    "03_semantic_vector",
    "04_delta",
    "05_svm_anchor",
    "06_contracts",
    "07_digest",
    "08_validation",
    "09_execution_permit",
    "10_state_machine",
    "11_state_record",
    "12_classification",
    "13_bug_fix",
    "14_plan_cluster",
    "15_handlers",
    "16_example",
    "17_communication",
    "18_conformance",
    "19_specs_base",
    "20_specs_agents",
    "21_skills_boundary",
    "22_specs_commands",
    "23_specs_github",
    "24_specs_policies",
    "25_specs_default",
    "26_specs_grounding",
    "27_runtime_dict",
    "28_runtime_render",
    "29_syntax",
    "30_epistemic",
    "31_prompt_ir",
    "_assemble_prompts_kernel",
]

_PRECOMPILE_IMPORTS: str = """\
import ast
from collections.abc import Mapping
from dataclasses import dataclass, field, asdict
from datetime import datetime, timezone
from pathlib import Path
import sys
from types import MappingProxyType
from typing import Optional, Any, Callable
from enum import Enum
import hashlib
import json
import math
import uuid
"""

# Subset of __init__ whitelist — symbols that start with _ but ARE public.
_PRECOMPILE_WHITELIST: frozenset[str] = frozenset({
    "_ALL_SPECS",
    "_SPEC_FIELDS",
    "_TIER_A_AGENTS",
    "_TIER_A_POLICIES",
    "_TIER_B_COMMANDS",
    "_KERNEL_SYMBOLS",
    "_PROJECTION_PREFIXES",
    "_FIELD_TO_IR",
    "_spec",
    "_validate_spec",
    "_count",
    "_render_runtime_mapping",
    "_render_spec_block",
    "_assemble_prompts_kernel",
})


def _precompiled_output_path(kernel_dir: Path | None = None) -> Path:
    """Path to the generated _kernel_precompiled.py artifact."""
    if kernel_dir is None:
        kernel_dir = Path(__file__).resolve().parent
    return kernel_dir / "_kernel_precompiled.py"


def assemble_precompiled_kernel(kernel_dir: Path | None = None) -> str:
    """Concatenate all kernel fragments into one importable Python module.

    Returns the complete source text for _kernel_precompiled.py.
    Build-time cross-validation of RUNTIME_RULES ↔ OWNERS ↔ WORKFLOWS
    is embedded as assert statements at the end of the module.
    """
    if kernel_dir is None:
        kernel_dir = Path(__file__).resolve().parent

    lines: list[str] = []
    lines.append('"""Precompiled opencode_prompts_kernel — generated by _assemble_prompts_kernel.')
    lines.append('')
    lines.append('DO NOT EDIT. Regenerate with: write_precompiled_kernel()')
    lines.append('"""')
    lines.append('from __future__ import annotations')
    lines.append('')

    # 1. Common imports
    lines.append('# === Common imports (shared by all fragments) ===')
    for imp_line in _PRECOMPILE_IMPORTS.strip().split('\n'):
        lines.append(imp_line)
    lines.append('')

    # 2. Fragment bodies with source annotations
    for name in _PRECOMPILE_FRAGMENTS:
        path = kernel_dir / f"{name}.py"
        if not path.is_file():
            raise FileNotFoundError(f"kernel fragment missing: {path}")
        src = path.read_text(encoding="utf-8")
        # Strip duplicate __future__ imports (already at top of precompiled module)
        lines_fragment = src.split('\n')
        cleaned: list[str] = []
        for line in lines_fragment:
            stripped = line.strip()
            if stripped.startswith('from __future__ import'):
                continue  # already at module top
            cleaned.append(line)
        src = '\n'.join(cleaned)
        lines.append(f'# === Fragment: {name}.py ===')
        lines.append(src.rstrip('\n'))
        lines.append('')

    # 3. Build __all__
    lines.append('# === __all__ computation (mirrors __init__._bootstrap) ===')
    lines.append('_pub = [')
    lines.append('    k for k in list(globals())')
    lines.append('    if not k.startswith("_")')
    lines.append(f'    or k in {sorted(_PRECOMPILE_WHITELIST)!r}')
    lines.append(']')
    lines.append('__all__ = sorted(_pub)')
    lines.append('')

    # 4. Build-time cross-validation
    lines.append('# === Build-time cross-validation ===')
    lines.append('# Guard: only run when RUNTIME_RULES has been defined (not during syntax check)')
    lines.append('if "RUNTIME_RULES" in dir():')
    lines.append('    _missing_owners = [k for k in RUNTIME_RULES if k not in RUNTIME_RULE_OWNERS]')
    lines.append('    assert not _missing_owners, f"RUNTIME_RULES keys without owner: {_missing_owners}"')
    lines.append('')
    lines.append('    _orphan_owners = [k for k in RUNTIME_RULE_OWNERS if k not in RUNTIME_RULES]')
    lines.append('    assert not _orphan_owners, f"RUNTIME_RULE_OWNERS keys without rule: {_orphan_owners}"')
    lines.append('')
    lines.append('    _reachable = set()')
    lines.append('    for _wf_name, _wf_rules in RUNTIME_WORKFLOWS.items():')
    lines.append('        for _r in _wf_rules:')
    lines.append('            if _r in RUNTIME_RULES:')
    lines.append('                _reachable.add(_r)')
    lines.append('    _unreachable = [k for k in RUNTIME_RULES if k not in _reachable]')
    lines.append('    assert not _unreachable, f"RUNTIME_RULES not reachable from any workflow: {_unreachable}"')
    lines.append('')

    return '\n'.join(lines)


def write_precompiled_kernel(kernel_dir: Path | None = None) -> int:
    """Write _kernel_precompiled.py. Returns byte count written."""
    body = assemble_precompiled_kernel(kernel_dir)
    output = _precompiled_output_path(kernel_dir)
    output.write_text(body, encoding="utf-8", newline="\n")
    # Verify it compiles
    compile(body, str(output), "exec")
    return len(body)
