// This file is auto-generated by wasm-pack.
// Rebuild with: cd packages/wasm/core && wasm-pack build --target bundler
//
// Stub for development — replace with actual wasm-pack output.

let wasm;

const cachedTextDecoder = new TextDecoder('utf-8', { ignoreBOM: true, fatal: true });
const cachedTextEncoder = new TextEncoder();

export async function __wbg_init(input) {
    if (wasm !== undefined) return wasm;
    if (typeof input === 'undefined') {
        input = new URL('opencode_wasm_bg.wasm', import.meta.url);
    }
    const imports = __wbg_get_imports();
    __wbg_init_memory(imports);
    const { instance, module } = await __wbg_load(input, imports);
    wasm = instance.exports.wasm;
    return __wbg_finalize_init(instance, module);
}

function __wbg_get_imports() {
    const imports = {};
    imports.wbg = {};
    return imports;
}

function __wbg_init_memory(imports) {
    imports.wbg.memory = new WebAssembly.Memory({ initial: 17, maximum: 65536 });
}

async function __wbg_load(input, imports) {
    if (typeof Response === 'function' && input instanceof Response) {
        if (typeof WebAssembly.instantiateStreaming === 'function') {
            try {
                return await WebAssembly.instantiateStreaming(input, imports);
            } catch (e) {
                if (input.headers.get('Content-Type') !== 'application/wasm') {
                    console.warn('wasm streaming failed, falling back to arrayBuffer', e);
                } else {
                    throw e;
                }
            }
        }
        const response = await input.arrayBuffer();
        return await WebAssembly.instantiate(response, imports);
    } else {
        const instance = await WebAssembly.instantiate(input, imports);
        if (instance instanceof WebAssembly.Instance) {
            return { instance, module: input };
        } else {
            return instance;
        }
    }
}

function __wbg_finalize_init(instance, module) {
    wasm = instance.exports.__wbindgen_wasm_module;
    return wasm;
}

/**
 * Parse code using the specified language and return a JSON AST.
 * @param {string} code
 * @param {string} language
 * @returns {string | undefined}
 */
export function parse(code, language) {
    // Stub implementation — replaced by wasm-pack build
    const ptr0 = 0;
    const len0 = 0;
    return undefined;
}

/**
 * Return an array of all available language names.
 * @returns {Array<any>}
 */
export function available_languages() {
    // Stub implementation — replaced by wasm-pack build
    const ret = [];
    return ret;
}

export default __wbg_init;
