// Generated by script/fetch-queries.ts — do not edit by hand.
// Refresh: bun run script/fetch-queries.ts --refresh
import query0 from "../../assets/queries/python-highlights-0.scm" with { type: "file" }
import query1 from "../../assets/queries/rust-highlights-0.scm" with { type: "file" }
import query2 from "../../assets/queries/go-highlights-0.scm" with { type: "file" }
import query3 from "../../assets/queries/cpp-highlights-0.scm" with { type: "file" }
import query4 from "../../assets/queries/csharp-highlights-0.scm" with { type: "file" }
import query5 from "../../assets/queries/bash-highlights-0.scm" with { type: "file" }
import query6 from "../../assets/queries/c-highlights-0.scm" with { type: "file" }
import query7 from "../../assets/queries/java-highlights-0.scm" with { type: "file" }
import query8 from "../../assets/queries/kotlin-highlights-0.scm" with { type: "file" }
import query9 from "../../assets/queries/ruby-highlights-0.scm" with { type: "file" }
import query10 from "../../assets/queries/php-highlights-0.scm" with { type: "file" }
import query11 from "../../assets/queries/scala-highlights-0.scm" with { type: "file" }
import query12 from "../../assets/queries/html-highlights-0.scm" with { type: "file" }
import query13 from "../../assets/queries/hcl-highlights-0.scm" with { type: "file" }
import query14 from "../../assets/queries/json-highlights-0.scm" with { type: "file" }
import query15 from "../../assets/queries/yaml-highlights-0.scm" with { type: "file" }
import query16 from "../../assets/queries/haskell-highlights-0.scm" with { type: "file" }
import query17 from "../../assets/queries/css-highlights-0.scm" with { type: "file" }
import query18 from "../../assets/queries/julia-highlights-0.scm" with { type: "file" }
import query19 from "../../assets/queries/lua-highlights-0.scm" with { type: "file" }
import query20 from "../../assets/queries/ocaml-highlights-0.scm" with { type: "file" }
import query21 from "../../assets/queries/clojure-highlights-0.scm" with { type: "file" }
import query22 from "../../assets/queries/swift-highlights-0.scm" with { type: "file" }
import query23 from "../../assets/queries/toml-highlights-0.scm" with { type: "file" }
import query24 from "../../assets/queries/nix-highlights-0.scm" with { type: "file" }
import query25 from "../../assets/queries/pascal-highlights-0.scm" with { type: "file" }
import query26 from "../../assets/queries/zig-highlights-0.scm" with { type: "file" }
import query27 from "../../assets/queries/markdown-highlights-0.scm" with { type: "file" }
import query28 from "../../assets/queries/markdown-injections-0.scm" with { type: "file" }
import query29 from "../../assets/queries/powershell-highlights-0.scm" with { type: "file" }

/** Query URL -> embedded asset path. Consumed by resolvedParsers in the TUI. */
export const embeddedQueryAssets = new Map<string, string>([
  ["https://github.com/tree-sitter/tree-sitter-python/raw/refs/heads/master/queries/highlights.scm", query0 as unknown as string],
  ["https://raw.githubusercontent.com/nvim-treesitter/nvim-treesitter/refs/heads/master/queries/rust/highlights.scm", query1 as unknown as string],
  ["https://raw.githubusercontent.com/nvim-treesitter/nvim-treesitter/refs/heads/master/queries/go/highlights.scm", query2 as unknown as string],
  ["https://raw.githubusercontent.com/nvim-treesitter/nvim-treesitter/refs/heads/master/queries/cpp/highlights.scm", query3 as unknown as string],
  ["https://raw.githubusercontent.com/nvim-treesitter/nvim-treesitter/refs/heads/master/queries/c_sharp/highlights.scm", query4 as unknown as string],
  ["https://raw.githubusercontent.com/nvim-treesitter/nvim-treesitter/refs/heads/master/queries/bash/highlights.scm", query5 as unknown as string],
  ["https://raw.githubusercontent.com/nvim-treesitter/nvim-treesitter/refs/heads/master/queries/c/highlights.scm", query6 as unknown as string],
  ["https://raw.githubusercontent.com/nvim-treesitter/nvim-treesitter/refs/heads/master/queries/java/highlights.scm", query7 as unknown as string],
  ["https://raw.githubusercontent.com/fwcd/tree-sitter-kotlin/0.3.8/queries/highlights.scm", query8 as unknown as string],
  ["https://raw.githubusercontent.com/nvim-treesitter/nvim-treesitter/refs/heads/master/queries/ruby/highlights.scm", query9 as unknown as string],
  ["https://github.com/tree-sitter/tree-sitter-php/raw/refs/heads/master/queries/highlights.scm", query10 as unknown as string],
  ["https://raw.githubusercontent.com/nvim-treesitter/nvim-treesitter/refs/heads/master/queries/scala/highlights.scm", query11 as unknown as string],
  ["https://github.com/tree-sitter/tree-sitter-html/raw/refs/heads/master/queries/highlights.scm", query12 as unknown as string],
  ["https://raw.githubusercontent.com/nvim-treesitter/nvim-treesitter/master/queries/hcl/highlights.scm", query13 as unknown as string],
  ["https://raw.githubusercontent.com/nvim-treesitter/nvim-treesitter/refs/heads/master/queries/json/highlights.scm", query14 as unknown as string],
  ["https://raw.githubusercontent.com/nvim-treesitter/nvim-treesitter/refs/heads/master/queries/yaml/highlights.scm", query15 as unknown as string],
  ["https://raw.githubusercontent.com/nvim-treesitter/nvim-treesitter/refs/heads/master/queries/haskell/highlights.scm", query16 as unknown as string],
  ["https://raw.githubusercontent.com/nvim-treesitter/nvim-treesitter/refs/heads/master/queries/css/highlights.scm", query17 as unknown as string],
  ["https://raw.githubusercontent.com/nvim-treesitter/nvim-treesitter/refs/heads/master/queries/julia/highlights.scm", query18 as unknown as string],
  ["https://raw.githubusercontent.com/tree-sitter-grammars/tree-sitter-lua/v0.5.0/queries/highlights.scm", query19 as unknown as string],
  ["https://raw.githubusercontent.com/nvim-treesitter/nvim-treesitter/refs/heads/master/queries/ocaml/highlights.scm", query20 as unknown as string],
  ["https://raw.githubusercontent.com/nvim-treesitter/nvim-treesitter/refs/heads/master/queries/clojure/highlights.scm", query21 as unknown as string],
  ["https://raw.githubusercontent.com/alex-pinkus/tree-sitter-swift/main/queries/highlights.scm", query22 as unknown as string],
  ["https://raw.githubusercontent.com/nvim-treesitter/nvim-treesitter/master/queries/toml/highlights.scm", query23 as unknown as string],
  ["https://raw.githubusercontent.com/nvim-treesitter/nvim-treesitter/refs/heads/master/queries/nix/highlights.scm", query24 as unknown as string],
  ["https://raw.githubusercontent.com/Isopod/tree-sitter-pascal/master/queries/highlights.scm", query25 as unknown as string],
  ["https://raw.githubusercontent.com/tree-sitter-grammars/tree-sitter-zig/master/queries/highlights.scm", query26 as unknown as string],
  ["https://raw.githubusercontent.com/nvim-treesitter/nvim-treesitter/master/queries/markdown/highlights.scm", query27 as unknown as string],
  ["https://raw.githubusercontent.com/nvim-treesitter/nvim-treesitter/master/queries/markdown/injections.scm", query28 as unknown as string],
  ["https://raw.githubusercontent.com/nvim-treesitter/nvim-treesitter/master/queries/powershell/highlights.scm", query29 as unknown as string],
])

export function embeddedQueryPath(url: string): string | undefined {
  return embeddedQueryAssets.get(url)
}

export const embeddedQueryPaths = [...embeddedQueryAssets.values()]
