/**
 * Default ignore patterns + union composer for the Fossil snapshot repo's
 * `.fossil-settings/ignore-glob`.
 *
 * User directive 2026-09-09: installation binaries (*.exe, *.dll), static
 * libraries and build/release output directories must NEVER be tracked —
 * "ни под каким соусом". Reference .gitignores: D:\zPascal\XEComponents,
 * D:\zPython\ADID_Python.
 *
 * Note: Fossil skips dotfiles/dot-dirs (e.g. .opencode/, .env, .git, .cache)
 * unless `--dotfiles` is passed, which the snapshot code never does. Defaults
 * therefore only cover non-dot names.
 *
 * Pure module: no Effect, no filesystem, no fossil binary on import —
 * safe for unit tests.
 */

/** Flat patterns (no `*name` twins here — expandGlob adds those centrally). */
export const DEFAULT_IGNORE_PATTERNS: readonly string[] = [
  // Fossil / runtime infrastructure
  "*.fsl",
  ".jj",
  ".git",
  "_FOSSIL_",
  "_fossil",
  ".fossil-settings",

  // opencode runtime data — gateway logs grow unbounded and would both slow
  // every snapshot and bloat the repo (user directive 2026-09-09).
  // Note: fossil skips dot-dirs anyway (no --dotfiles), but these are belt &
  // suspenders for the gitignore side where dot-dirs ARE scanned.
  ".opencode/data",
  ".opencode/data/gateway",
  ".opencode/data/log",

  // Executables and shared libraries — never snapshot
  "*.exe",
  "*.dll",
  "*.ocx",
  "*.bpl",
  "*.so",
  "*.dylib",
  "*.pdb",

  // Static / object libraries, compiler intermediates
  "*.lib",
  "*.a",
  "*.o",
  "*.obj",
  "*.dcu",
  "*.dcp",
  "*.dcpil",
  "*.bpi",
  "*.dres",
  "*.res",
  "*.map",
  "*.tds",
  "*.drc",
  "*.rsm",
  "*.identcache",
  "*.ppu",

  // IDE / project local settings (Delphi-style, non-dot)
  "*.local",
  "*.dsk",
  "*.dof",
  "*.cfg",
  "*.stat",
  "*.tvsconfig",
  "*.projdata",
  "*.tbl2",
  "*.RTD",

  // ML model weights / vector store files — never snapshot (can be GBs)
  "*.gguf",
  "*.ggml",
  "*.safetensors",
  "*.pt",
  "*.pth",
  "*.onnx",
  "*.ckpt",
  "*.h5",
  "*.hdf5",
  "*.pb",
  "*.tflite",
  "*.bin",
  "*.faiss",
  "*.ann",
  "*.hnsw",
  "*.lance",

  // Build / release output directories
  "build",
  "dist",
  "releases",
  "release",
  "Release",
  "Debug",
  "Win32",
  "Win64",
  "OSX32",
  "OSX64",
  "Linux64",
  "Android",
  "iOSDevice32",
  "iOSDevice64",
  "iOSSimulator",
  "obj",
  "bin",
  "bin_tst",
  "out",
  "target",
  "__pycache__",
  "__history",
  "Backup",
  "backup",
  "bak",

  // Dependency / environment directories
  "node_modules",
  "venv",

  // Local model / vector-DB stores (embeddings, RAG runtimes)
  "models",
  "_models",
  "model_store",
  "vectorstore",
  "vectordb",
  "vector_db",
  "chroma",
  "qdrant",
  "lancedb",

  // Vendored / external dependencies (checked out libs, SDK trees)
  "external",
  "vendor",
  "third_party",

  // Local config directories (installation/project config, not sources)
  "config",

  // Our own toolchain (opencode.exe, opencode-markdownify.exe, opentui.dll,
  // fossil.exe, cmd_runner.exe, adm.exe) is already covered by the global
  // "*.exe" / "*.dll" patterns above — no explicit names needed. The tools/
  // DIRECTORY itself is never ignored: project sources may have one
  // (user directive 2026-09-09).

  // Python artifacts (note: __pycache__/ dir already above)
  "*.py[cod]",
  "*.pyd",
  "*.egg-info",

  // Secrets — installation config and crypto material
  "config.json",
  "config.json.enc",
  "gateway.jsonc",
  "auth.json",
  "*.enc",
  "*.key",
  "*.pem",
  "*.p12",
  "*.pfx",
  "*.kdbx",

  // Databases (binary data stores)
  "*.db",
  "*.sqlite",
  "*.sqlite3",
  "*.fdb",
  "*.gdb",
  "*.ib",

  // Logs / temp / backup files
  "logs",
  "*.log",
  "tmp",
  "temp",
  "*.tmp",
  "*.temp",
  "*.bak",
  "*.old",
  "*.orig",
  "*.backup_*",
  "*.baseline",
  "*.bk?",
  "*~",

  // Archives (artifact stores, not sources)
  "*.zip",
  "*.7z",
  "*.rar",
  "*.tar",
  "*.gz",

  // OS noise
  "Thumbs.db",
  "Desktop.ini",
  "ehthumbs.db",
]

/**
 * Sectioned .gitignore header block for newly created projects.
 * Same DEFAULT_IGNORE_PATTERNS source — one truth for both fossil ignore-glob
 * and the project .gitignore written by Config.ensureGitignore.
 * Git syntax: bare names already match at any depth in git; no twin expansion
 * needed. Fossil-only twins are NOT emitted here.
 */
export const PROJECT_GITIGNORE_HEADER = [
  "# Generated by opencode — default ignore block (user directive 2026-09-09).",
  "# Add project-specific patterns BELOW this block; do not remove defaults.",
  ...DEFAULT_IGNORE_PATTERNS.filter((p) => p !== ".git" && p !== "_FOSSIL_" && p !== "_fossil" && p !== ".jj"),
]

/**
 * Union composer: defaults first, then translated .gitignore lines, then
 * existing manual lines from the current ignore-glob file. Dedup keeps first
 * occurrence; manual lines therefore survive every regeneration
 * (fix for the old overwrite semantics that silently dropped hand edits).
 *
 * Defaults get Fossil twin expansion (bare name only covers the worktree
 * root — "*name" covers nested paths too, e.g. packages/x/node_modules).
 * Gitignore lines arrive pre-expanded from translateGitignore(); manual
 * existing lines are kept literal (user's explicit globs).
 */
export function composeIgnoreGlob(
  gitignoreLines: readonly string[],
  existingLines: readonly string[],
): string[] {
  const out: string[] = []
  const seen = new Set<string>()
  const push = (raw: string) => {
    const p = raw.trim()
    if (!p || seen.has(p)) return
    seen.add(p)
    out.push(p)
  }
  for (const p of DEFAULT_IGNORE_PATTERNS) {
    // Twin only bare names that don't already start with a wildcard.
    if (p.includes("/") || p.startsWith("*")) push(p)
    else {
      push(p)
      push(`*${p}`)
    }
  }
  for (const p of gitignoreLines) push(p)
  for (const p of existingLines) push(p)
  return out
}
