import type { TokenizerModel, TokenizerInstance } from "../types"
import { BPETokenizer } from "../bpe-encoder"
import * as Log from "@opencode-ai/core/util/log"

const log = Log.create({ service: "tokenizer.deepseek-v4" })

let tokenizer: BPETokenizer | undefined
let loadAttempted = false

async function loadModel(): Promise<TokenizerModel | undefined> {
  // Load via Bun.file to avoid static import requirement (model.json
  // is generated by scripts/fetch-deepseek-tokenizer.ts and may not
  // exist during development).
  try {
    const rawPath = new URL("./model.json", import.meta.url).pathname
    // On Windows, URL.pathname prefixes with "/" (e.g. "/D:/...")
    const path = process.platform === "win32" ? rawPath.slice(1) : rawPath
    const file = Bun.file(path)
    if (!(await file.exists())) return undefined
    return (await file.json()) as TokenizerModel
  } catch {
    return undefined
  }
}

export async function loadDeepSeekV4(): Promise<TokenizerInstance | undefined> {
  if (tokenizer) return tokenizer
  if (loadAttempted) return undefined

  loadAttempted = true
  const model = await loadModel()
  if (!model) {
    log.debug("model.json not found, tokenizer unavailable — fallback to /4 heuristic")
    return undefined
  }
  tokenizer = new BPETokenizer(model)
  log.debug("tokenizer loaded", { vocabSize: model.vocabSize })
  return tokenizer
}

/** Synchronous get — returns undefined if not yet loaded */
export function getDeepSeekV4(): TokenizerInstance | undefined {
  return tokenizer
}

/** Pre-load during startup to avoid first-call latency */
export function preloadDeepSeekV4(): void {
  loadDeepSeekV4()
}

export * as DeepSeekV4Loader from "./loader"
