@echo off
rem Initializes RAD Studio / Delphi environment variables for MSBuild.
rem Generated by: adm --init-delphi

rem Usage:
rem   call tools\init_delphi.cmd
rem   call tools\init_delphi.cmd Win64
rem   call tools\init_delphi.cmd Linux64
rem PowerShell note: running a .cmd does NOT persist env into PowerShell.
rem   Use:  . .\tools\init_delphi.ps1 -Platform Win64

set "DEFAULT_PLATFORM=Win64"
set "PLATFORM=%~1"
if not defined PLATFORM set "PLATFORM=%DEFAULT_PLATFORM%"

rem --- Dynamic Delphi root discovery via where.exe ---
set "DELPHI_ROOT="
for /f "delims=" %%F in ('where dcc64 2^>nul') do (
  if not defined DELPHI_ROOT (
    for %%D in ("%%~dpF..") do set "DELPHI_ROOT=%%~fD"
  )
)
if not defined DELPHI_ROOT (
  for /f "delims=" %%F in ('where dcc32 2^>nul') do (
    if not defined DELPHI_ROOT (
      for %%D in ("%%~dpF..") do set "DELPHI_ROOT=%%~fD"
    )
  )
)
if not defined DELPHI_ROOT (
  set "DELPHI_ROOT=D:\USESoft\RAD_Pascal"
)

set "RSVARS=%DELPHI_ROOT%\bin\rsvars.bat"
set "RSVARS64=%DELPHI_ROOT%\bin64\rsvars64.bat"

if /I "%PLATFORM%"=="Win64" (
  if exist "%RSVARS64%" (
    call "%RSVARS64%"
  ) else (
    call "%RSVARS%"
  )
) else if /I "%PLATFORM%"=="Linux64" (
  if exist "%RSVARS64%" (
    call "%RSVARS64%"
  ) else (
    call "%RSVARS%"
  )
) else (
  call "%RSVARS%"
)
if errorlevel 1 (
  echo [ERROR] rsvars.bat failed.
  exit /b 1
)

where dcc32
if errorlevel 1 (
  echo [ERROR] dcc32.exe not found after rsvars.
  exit /b 1
)
echo [OK] Delphi environment initialized.
echo [INFO] default_platform=Win64
echo [INFO] detected_root=%DELPHI_ROOT%
echo.
echo Examples:
echo   tools\build_delphi_msbuild.cmd delphi\ADIDInstallerFMX.dpr Win32 Release
echo   tools\build_delphi_msbuild.cmd delphi\ADIDInstallerFMX.dpr Win64 Release
echo   tools\build_delphi_msbuild.cmd delphi\ADIDInstallerFMX.dpr Linux64 Release my_wsl_profile
echo.
rem Notes:
rem - Delphi 2009+ uses /p:config=<ConfigName> (StackOverflow 558147)
rem - Delphi 2007 uses /p:Configuration=<ConfigName>
exit /b 0
