# Initializes RAD Studio / Delphi environment variables for MSBuild in this PowerShell session.
# Generated by: adm --init-delphi

# IMPORTANT: dot-source this script to keep env in the current session:
#   . .\tools\init_delphi.ps1 -Platform Win32

param(
  [ValidateSet('Win32','Win64','Linux64')]
  [string]$Platform = 'Win64'
)

$ErrorActionPreference = 'Stop'

# Dynamic Delphi root discovery via where.exe
$dcc = Get-Command dcc64 -ErrorAction SilentlyContinue
if (-not $dcc) { $dcc = Get-Command dcc32 -ErrorAction SilentlyContinue }
if ($dcc) {
  $delphiRoot = Split-Path (Split-Path $dcc.Source -Parent) -Parent
} else {
  $delphiRoot = "D:\USESoft\RAD_Pascal"
}

$rsvars = Join-Path $delphiRoot 'bin\rsvars.bat'
$rsvars64 = Join-Path $delphiRoot 'bin64\rsvars64.bat'
$bat = if ($Platform -in @('Win64','Linux64')) {
  if (Test-Path $rsvars64) { $rsvars64 } else { $rsvars }
} else { $rsvars }
if (-not (Test-Path -LiteralPath $bat)) {
  Write-Error "rsvars script not found: $bat"
}

$cmdLine = ('call "{0}" >nul && set' -f $bat)
$envBlock = & cmd.exe /d /s /c $cmdLine
foreach ($line in $envBlock) {
  $idx = $line.IndexOf('=')
  if ($idx -lt 1) { continue }
  $name = $line.Substring(0, $idx)
  $value = $line.Substring($idx + 1)
  if ($name -eq 'PROMPT') { continue }
  [System.Environment]::SetEnvironmentVariable($name, $value, 'Process')
}

Write-Host "[OK] Delphi environment initialized for $Platform."
Write-Host "default_platform=Win64"
Write-Host "detected_root=$delphiRoot"
Write-Host "Example: .\\tools\\build_delphi_msbuild.ps1 -Dpr delphi\\ADIDInstallerFMX.dpr -Platform $Platform -Config Release"
Write-Host "Linux note: FMX only; typically also pass -Profile (Remote Profile name)."
Write-Host ("dcc32=" + [bool](Get-Command dcc32 -ErrorAction SilentlyContinue))
Write-Host ("BDS=" + $env:BDS)
