@echo off
rem Initializes an MSVC build environment for this terminal.
rem Generated by: adm --init-msvc

rem IMPORTANT: run via `call` so environment stays in the current cmd.exe session.
rem   call tools\init_msvc.cmd
rem PowerShell note: running a .cmd does NOT persist env into PowerShell.
rem   Use:  . .\tools\init_msvc.ps1

where cl >nul 2>&1
if not errorlevel 1 (
  where msbuild >nul 2>&1
  if not errorlevel 1 (
    echo [OK] MSVC environment already initialized.
    exit /b 0
  )
)

call "C:\Program Files\Microsoft Visual Studio\18\Community\Common7\Tools\VsDevCmd.bat" -arch=x64 -host_arch=x64
if errorlevel 1 (
  echo [ERROR] VsDevCmd failed.
  exit /b 1
)

where cl
if errorlevel 1 (
  echo [ERROR] cl.exe not found after VsDevCmd.
  exit /b 1
)
where msbuild
if errorlevel 1 (
  echo [ERROR] msbuild.exe not found after VsDevCmd.
  exit /b 1
)
echo [OK] MSVC environment initialized.
exit /b 0
